### ISSUE TITLE
Tensorflow placeholder error

### ISSUE THREAD

**Issue by nitinmeharia** [monikkinom/ner-lstm#13]
WARNING:tensorflow:From model.py:99 in train.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Traceback (most recent call last):
  File "model.py", line 146, in <module>
    train(parser.parse_args())
  File "model.py", line 99, in train
    model = Model(args)
  File "/Users/kumarnitin/Code/chanakya/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/Users/kumarnitin/Code/chanakya/venv/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 943, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (4, 30, 111) for Tensor u'Placeholder:0', which has shape '(?, 1000, 100)'

**Comment by monikkinom** [comment]
Solved here: https://github.com/monikkinom/ner-lstm/issues/14
